export const FETCH_PLACES = 'FETCH_PLACES';
export const GET_SAVED_PLACES = 'GET_SAVED_PLACES';
export const SAVE_PLACE = 'SAVE_PLACE';
export const DELETE_PLACE = 'DELETE_PLACE';
export const CLEAR_PLACE_STATE = 'CLEAR_PLACE_STATE';